# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
#srs_log_tank        file;
srs_log_level       trace;
#pid                 /var/run/srs/srs.pid;
#srs_log_file        /var/log/srs/srs.log;

http_server {
    enabled         on;
    listen          8080;
    dir             /usr/local/srs/objs/nginx/html;
}

vhost __defaultVhost__ {
    # HLS 配置
    hls {
        enabled         on;
        hls_path       /usr/local/srs/objs/nginx/html;
        hls_fragment   10;
        hls_window     600;
    }

    # HTTP-FLV 配置
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    # 回调配置
    http_hooks {
        enabled         on;
        on_publish      http://nginx:8009/api/v1/internal/srs/on_publish;
        on_unpublish    http://nginx:8009/api/v1/internal/srs/on_unpublish;
    }
}